### ISSUE TITLE
Provide method to handle errors

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/tc-bus-api-wrapper#1]
Update wrapper to provide a method to which we can pass errors, which in turn calls [postEvent](https://github.com/topcoder-platform/tc-bus-api-wrapper/blob/b8c0793b3032fd3f529b13461427371174a51077/docs/EventsApi.md#postevent).

The method will always use the same kafka topic to post to - the callee will not be passing the topic to use.

**Comment by callmekatootie** [comment]
Assigned ticket to SharathKumar92

**Comment by sharathkumaranbu** [comment]
Sure. I think the same approach is used in m2m module of tc-core-library-js. I will follow the same.
