### ISSUE TITLE
Update tc-core-library-js version

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/tc-bus-api-wrapper#9]
Need to use https://github.com/appirio-tech/tc-core-library-js/tree/v2.6.4 to get rid of security vulnerabilities and ensure that it is not being passed on to the other modules using it

**Comment by callmekatootie** [comment]
This is now resolved in `1.2.0`. Now, I am not sure if I need to do a manual release to npm or if it gets done automatically... :thinking: Do you happen to know that or should we check with @cwdcwd ?

**Comment by sharathkumaranbu** [comment]
@callmekatootie You would need to publish the current master branch as version 1.2.0 in https://github.com/topcoder-platform/tc-bus-api-wrapper/releases. Then it will get auto deployed to npm as well. I doesn't seem to have maintainer access to this repo, hence I am unable to publish it. Could you please do the needful.

**Comment by callmekatootie** [comment]
Version 1.2.0 published - https://github.com/topcoder-platform/tc-bus-api-wrapper/releases/tag/v1.2.0

**Comment by sharathkumaranbu** [comment]
@callmekatootie Tests seem to have failed while publishing in npm. One test seem to have failed. https://app.circleci.com/jobs/github/topcoder-platform/tc-bus-api-wrapper/27

**Comment by callmekatootie** [comment]
I am not sure about that - perhaps we need to rerun... weirdly enough, I have set timeout to 30,000 and yet it times out after 10,000

**Comment by callmekatootie** [comment]
@cwdcwd Could you kindly rerun the CI

**Comment by callmekatootie** [comment]
Closing ticket. Issue resolved
